In [2]:
import pandas as pd
import numpy as py
import sys, os

In [3]:
#chrom, pos, alignstrand, loc_in_ref, readname, strand,
#k_mer, signal_means, signal_stds, signal_lens,
#cent_signals, methy_label
input_path='/fastscratch/c-panz/2021-11-26'
df_train=pd.read_csv(os.path.join(input_path, 'feature.train.tsv'),
                     sep = '\t', header = None)
df_valid=pd.read_csv(os.path.join(input_path, 'feature.valid.tsv'),
                     sep = '\t', header = None)
df_train.shape, df_valid.shape

((225280, 12), (8584, 12))

In [37]:
df_train.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11
0,KJ477685.1,12039,-,154776,56c51110-634d-41ae-87fb-494adb6d5280,t,ATAGTCATCGTTATCGT,"-1.18811,1.231525,-0.721006,-1.506361,0.806286...","0.401242,0.184347,0.178917,0.178138,0.071266,0...","6,20,17,15,3,12,15,3,33,8,15,3,7,3,18,13,8","-1.767628,-1.523417,-0.604715,-1.383867,-0.930...",2
1,J02459.1,22351,-,26150,9dec6434-a448-403e-b24c-7c12a44ee085,t,CCGCCTCCCGGATCCGG,"0.237093,0.160368,-0.295509,0.608267,-0.209921...","0.061181,0.13778,0.12681,0.085879,0.090791,0.0...","3,13,31,10,17,13,3,28,3,20,19,19,6,3,9,3,18","0.31885,0.171688,0.220742,0.220742,0.306586,0....",0
2,KJ477685.1,56253,-,110562,86925072-4ce5-4afc-9baf-03949dd4c079,t,GAAATTATCGATCATAA,"-0.052652,-0.639794,-0.953446,-0.978426,1.2677...","0.153596,0.07349,0.074479,0.04246,0.228586,0.2...","65,9,9,3,24,27,16,3,49,20,18,3,5,33,20,9,6","0.174868,0.274792,0.049962,0.062453,-0.012491,...",2

In [4]:
import tensorflow as tf

In [38]:
def parse_a_line_b(value, base_num, signal_num):
    vec = tf.decode_raw(value, tf.int8)

    bases = tf.cast(tf.reshape(tf.strided_slice(vec, [0], [base_num]), [base_num]), dtype=tf.int32)
    means = tf.bitcast(
        tf.reshape(tf.strided_slice(vec, [base_num], [base_num + base_num * 4]), [base_num, 4]),
        type=tf.float32)
    stds = tf.bitcast(
        tf.reshape(tf.strided_slice(vec, [base_num * 5], [base_num * 5 + base_num * 4]), [base_num, 4]),
        type=tf.float32)
    sanum = tf.cast(tf.bitcast(
        tf.reshape(tf.strided_slice(vec, [base_num * 9], [base_num * 9 + base_num * 2]), [base_num, 2]),
        type=tf.int16), dtype=tf.int32)
    signals = tf.bitcast(
        tf.reshape(tf.strided_slice(vec, [base_num * 11], [base_num * 11 + 4 * signal_num]),
                   [signal_num, 4]), type=tf.float32)
    labels = tf.cast(
        tf.reshape(tf.strided_slice(vec, [base_num * 11 + signal_num * 4], [base_num * 11 + signal_num * 4 + 1]),
                   [1]),
        dtype=tf.int32)

    return bases, means, stds, sanum, signals, labels

base2code_dna = {'A': 0, 'C': 1, 'G': 2, 'T': 3, 'N': 4}

def parse_a_line(line):
    def _kmer2code(kmer_bytes):
        return np.array([base2code_dna[x] for x in kmer_bytes.decode("utf-8")], np.int32)

    words = tf.decode_csv(line, [[""]] * 12, "\t")

    kmer = tf.py_func(_kmer2code, [words[6]], tf.int32)
    base_mean = tf.string_to_number(tf.string_split([words[7]], ",").values, tf.float32)
    base_std = tf.string_to_number(tf.string_split([words[8]], ",").values, tf.float32)
    base_signal_len = tf.string_to_number(tf.string_split([words[9]], ",").values, tf.int32)
    cent_signals = tf.string_to_number(tf.string_split([words[10]], ",").values, tf.float32)
    label = tf.string_to_number(words[11], tf.int32)

    return kmer, base_mean, base_std, base_signal_len, cent_signals, label

In [43]:
#words = tf.decode_csv('/fastscratch/c-panz/2021-11-26/feature.train.tsv', [[""]] * 12, "\t")
valid_file='/fastscratch/c-panz/2021-11-26/feature.valid.tsv'
valid_dataset = tf.data.TextLineDataset([valid_file]).map(parse_a_line)
valid_dataset

# Split train and test

In [3]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV, StratifiedKFold, GridSearchCV, RepeatedStratifiedKFold
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import EditedNearestNeighbours, RandomUnderSampler
from imblearn.pipeline import Pipeline as imbpipeline
from imblearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, f1_score

from collections import Counter


df_lambda_5mC_train, df_lambda_5mC_test = train_test_split(df_lambda_5mC,
                                                           train_size=0.5,
                                                           random_state=42)

df_lambda_5C_train, df_lambda_5C_test = train_test_split(df_lambda_5C,
                                                         train_size=0.5,
                                                         random_state=42)

NameError: name 'df_lambda_5mC' is not defined

In [ ]:
df_lambda_5mC_train.shape, df_lambda_5C_train.shape

In [37]:
X_train = pd.concat([df_lambda_5mC_train, df_lambda_5C_train], axis=0).reset_index(drop=True)
X_test = pd.concat([df_lambda_5mC_test, df_lambda_5C_test], axis=0).reset_index(drop=True)

In [38]:
X_train.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11
0,J02459.1,1479,+,1479,53e29230-e4a4-4427-ac0f-58e21bcf7a45,t,AGAGACGCCGTTTGGCC,"-0.447738,-0.75776,-0.776912,-1.042961,-0.5589...","0.132174,0.082434,0.063395,0.127124,0.115171,0...","26,3,5,6,12,7,15,18,3,5,7,21,73,3,36,15,13","-0.46215,-0.362226,-0.374717,-0.362226,-0.4871...",1
1,J02459.1,8634,+,8634,2abe484a-48eb-4ac0-8fbd-7f540f5e2c46,t,GGTCGCCCCGCTGTTTT,"-0.251688,-1.132387,0.855904,0.145893,-0.57564...","0.090037,0.277638,0.044496,0.07361,0.083657,0....","14,8,5,11,12,26,18,3,3,5,8,48,10,7,19,13,30","-0.255841,-0.081404,-0.232583,-0.197695,-0.174...",1
2,J02459.1,10559,-,37942,d95aa0fb-3ab4-4b4d-b4d6-f1b4141d2c49,t,GACCAGATCGCCTACCG,"-1.554025,-0.756328,1.181321,0.752899,-0.42717...","0.103933,0.111726,0.115112,0.08139,0.119942,0....","5,15,14,16,12,42,9,25,3,14,7,7,8,7,7,7,10","-1.578306,-1.605286,-1.632265,-1.605286,-1.348...",1

In [39]:
X_train.tail(3)

,0,1,2,3,4,5,6,7,8,9,10,11
8997,J02459.1,8267,+,8267,dc898ea0-080a-415c-97b3-a4c1423cffeb,t,GCAGGCGTCGTAAAAAG,"0.126927,0.953483,-0.375568,-1.072495,-0.31203...","0.122529,0.117534,0.282255,0.129901,0.243602,0...","20,12,8,44,18,20,7,6,5,36,37,43,22,43,3,12,3","0.098108,0.282059,0.220742,0.282059,0.159425,0...",0
8998,J02459.1,29204,-,19297,ac08e884-af04-4af1-b610-b1852c5e7609,t,GACTGCTACGACCACTG,"-0.890537,-1.003705,0.405333,1.035824,0.033122...","0.121901,0.094497,0.134596,0.143695,0.133681,0...","16,3,49,6,8,3,19,17,6,32,19,21,23,69,25,30,41","-0.614267,-0.686534,-0.927423,-0.951512,-1.023...",0
8999,J02459.1,19032,-,29469,b73bb5cb-93ed-41d8-9ddb-1b50a03a2010,t,CCACCTTCCGCACGGGC,"0.413527,0.285782,-0.029564,0.612762,-0.52273,...","0.103299,0.116446,0.114766,0.10733,0.13682,0.1...","3,11,77,40,5,17,15,7,12,37,7,11,3,3,21,17,3","0.409512,0.542001,0.289067,0.469734,0.385423,0...",0

In [36]:
input_path='/fastscratch/c-panz/2021-11-21'
X_train.to_csv(os.path.join(input_path, 'train.tsv'), 
               header = None, index = None, sep = '\t')
X_test.to_csv(os.path.join(input_path, 'test.tsv'), 
               header = None, index = None, sep = '\t')