In [1]:
import pandas as pd
import numpy as py
import sys, os

In [14]:
input_path='/fastscratch/c-panz/2021-11-21'
df_lambda_5mC = pd.read_csv(os.path.join(input_path, 'lambda_5mC.test.tsv'), header=None, sep ='\t')
df_lambda_5C = pd.read_csv(os.path.join(input_path, 'lambda_5C.test.tsv'), header=None, sep ='\t')
df_lambda_5mC

,0,1,2,3,4,5,6,7,8,9,10,11
0,J02459.1,14172,-,34329,dd393274-56bd-4c88-a4e2-6cfdcf498652,t,GCGCACATCGCCGGGCG,"-0.944506,0.115721,-0.559751,0.396759,-0.23408...","0.071109,0.076074,0.233221,0.140587,0.423872,0...","24,20,37,6,10,52,6,6,20,6,17,6,3,18,6,12,16","-0.938996,-1.058023,-0.978671,-0.938996,-0.991...",1
1,J02459.1,14169,-,34332,dd393274-56bd-4c88-a4e2-6cfdcf498652,t,CACATCGCCGGGCGTGC,"0.396759,-0.234088,0.361406,-0.513582,1.421719...","0.140587,0.423872,0.187783,0.152218,0.129525,0...","6,10,52,6,6,20,6,17,6,3,18,6,12,16,5,17,7","0.119028,0.383533,0.47611,0.423209,0.396759,0....",1
2,J02459.1,14165,-,34336,dd393274-56bd-4c88-a4e2-6cfdcf498652,t,TCGCCGGGCGTGCGCCA,"1.421719,0.162671,-0.584117,0.827748,0.614976,...","0.129525,0.139281,0.063618,0.175867,0.099776,0...","6,20,6,17,6,3,18,6,12,16,5,17,7,7,18,28,9","1.335754,1.547359,1.229952,1.362205,1.613485,1...",1
3,J02459.1,14161,-,34340,dd393274-56bd-4c88-a4e2-6cfdcf498652,t,CGGGCGTGCGCCAGAAT,"0.614976,-0.70094,-1.125619,-0.916954,0.187358...","0.099776,0.216776,0.088156,0.179991,0.136466,0...","6,3,18,6,12,16,5,17,7,7,18,28,9,14,6,3,9","0.819968,0.529012,0.515786,0.608363,0.595138,0...",1
4,J02459.1,14152,-,34349,dd393274-56bd-4c88-a4e2-6cfdcf498652,t,GCCAGAATCGCTGATTC,"-0.629146,1.141783,0.772262,-0.301243,-1.16382...","0.040522,0.075589,0.11428,0.173759,0.112997,0....","7,18,28,9,14,6,3,9,16,26,14,6,28,3,16,5,29","-0.67449,-0.568687,-0.634814,-0.608363,-0.5819...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,J02459.1,34717,+,34717,d9581437-d9ae-4cf5-94b9-b99bc3fa1ef8,t,ATTGCCAGCGCCAGATA,"-0.975601,0.548023,0.667464,-0.059018,0.655754...","0.109067,0.190954,0.072903,0.423556,0.142534,0...","7,3,6,5,3,3,12,24,12,48,3,6,6,5,3,16,8","-0.871216,-0.969579,-0.82906,-0.927423,-1.1241...",1
7996,J02459.1,34730,+,34730,d9581437-d9ae-4cf5-94b9-b99bc3fa1ef8,t,GATATAAGCGATTTAAG,"-2.065625,-1.288088,1.158401,-0.282794,1.10809...","0.095718,0.382998,0.315345,0.241189,0.1398,0.1...","5,3,16,8,7,6,8,34,24,9,7,3,18,3,8,21,7","-2.093729,-2.17804,-2.121832,-2.037521,-1.8970...",1
7997,J02459.1,34748,+,34748,d9581437-d9ae-4cf5-94b9-b99bc3fa1ef8,t,TAAGAAAACGCATTAAG,"0.992062,-0.239551,-0.585495,-1.250616,-1.1562...","0.288745,0.080135,0.148859,0.06979,0.127182,0....","5,21,6,3,7,7,45,16,8,7,6,22,7,12,6,9,3","0.576127,1.405187,1.208461,0.927423,0.843112,-...",1
7998,J02459.1,34765,+,34765,d9581437-d9ae-4cf5-94b9-b99bc3fa1ef8,t,ATGCAAAACGATAAAGT,"-1.702618,0.941475,-0.138957,0.783392,-0.26932...","0.041698,0.163751,0.080707,0.202019,0.097495,0...","6,10,9,12,6,27,4,19,11,15,3,6,8,19,9,3,5","-1.72838,-1.756484,-1.630017,-1.700276,-1.7283...",1
7999,J02459.1,34775,+,34775,d9581437-d9ae-4cf5-94b9-b99bc3fa1ef8,t,ATAAAGTGCGATCAGTA,"-1.316192,0.983631,-0.119441,-0.633813,-1.3364...","0.06319,0.526023,0.119854,0.175146,0.152706,0....","3,6,8,19,9,3,5,10,13,19,3,9,8,3,6,10,3","-1.264668,-1.27872,-1.405187,-0.126467,1.44734...",1

# Split train and test

In [21]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV, StratifiedKFold, GridSearchCV, RepeatedStratifiedKFold
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import EditedNearestNeighbours, RandomUnderSampler
from imblearn.pipeline import Pipeline as imbpipeline
from imblearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, f1_score

from collections import Counter


df_lambda_5mC_train, df_lambda_5mC_test = train_test_split(df_lambda_5mC,
                                                           train_size=0.5,
                                                           random_state=42)

df_lambda_5C_train, df_lambda_5C_test = train_test_split(df_lambda_5C,
                                                         train_size=0.5,
                                                         random_state=42)

In [22]:
df_lambda_5mC_train.shape, df_lambda_5C_train.shape

((4000, 12), (5000, 12))

In [37]:
X_train = pd.concat([df_lambda_5mC_train, df_lambda_5C_train], axis=0).reset_index(drop=True)
X_test = pd.concat([df_lambda_5mC_test, df_lambda_5C_test], axis=0).reset_index(drop=True)

In [38]:
X_train.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11
0,J02459.1,1479,+,1479,53e29230-e4a4-4427-ac0f-58e21bcf7a45,t,AGAGACGCCGTTTGGCC,"-0.447738,-0.75776,-0.776912,-1.042961,-0.5589...","0.132174,0.082434,0.063395,0.127124,0.115171,0...","26,3,5,6,12,7,15,18,3,5,7,21,73,3,36,15,13","-0.46215,-0.362226,-0.374717,-0.362226,-0.4871...",1
1,J02459.1,8634,+,8634,2abe484a-48eb-4ac0-8fbd-7f540f5e2c46,t,GGTCGCCCCGCTGTTTT,"-0.251688,-1.132387,0.855904,0.145893,-0.57564...","0.090037,0.277638,0.044496,0.07361,0.083657,0....","14,8,5,11,12,26,18,3,3,5,8,48,10,7,19,13,30","-0.255841,-0.081404,-0.232583,-0.197695,-0.174...",1
2,J02459.1,10559,-,37942,d95aa0fb-3ab4-4b4d-b4d6-f1b4141d2c49,t,GACCAGATCGCCTACCG,"-1.554025,-0.756328,1.181321,0.752899,-0.42717...","0.103933,0.111726,0.115112,0.08139,0.119942,0....","5,15,14,16,12,42,9,25,3,14,7,7,8,7,7,7,10","-1.578306,-1.605286,-1.632265,-1.605286,-1.348...",1

In [39]:
X_train.tail(3)

,0,1,2,3,4,5,6,7,8,9,10,11
8997,J02459.1,8267,+,8267,dc898ea0-080a-415c-97b3-a4c1423cffeb,t,GCAGGCGTCGTAAAAAG,"0.126927,0.953483,-0.375568,-1.072495,-0.31203...","0.122529,0.117534,0.282255,0.129901,0.243602,0...","20,12,8,44,18,20,7,6,5,36,37,43,22,43,3,12,3","0.098108,0.282059,0.220742,0.282059,0.159425,0...",0
8998,J02459.1,29204,-,19297,ac08e884-af04-4af1-b610-b1852c5e7609,t,GACTGCTACGACCACTG,"-0.890537,-1.003705,0.405333,1.035824,0.033122...","0.121901,0.094497,0.134596,0.143695,0.133681,0...","16,3,49,6,8,3,19,17,6,32,19,21,23,69,25,30,41","-0.614267,-0.686534,-0.927423,-0.951512,-1.023...",0
8999,J02459.1,19032,-,29469,b73bb5cb-93ed-41d8-9ddb-1b50a03a2010,t,CCACCTTCCGCACGGGC,"0.413527,0.285782,-0.029564,0.612762,-0.52273,...","0.103299,0.116446,0.114766,0.10733,0.13682,0.1...","3,11,77,40,5,17,15,7,12,37,7,11,3,3,21,17,3","0.409512,0.542001,0.289067,0.469734,0.385423,0...",0

In [36]:
input_path='/fastscratch/c-panz/2021-11-21'
X_train.to_csv(os.path.join(input_path, 'train.tsv'), 
               header = None, index = None, sep = '\t')
X_test.to_csv(os.path.join(input_path, 'test.tsv'), 
               header = None, index = None, sep = '\t')