# 2021/11/07
The jupypter notebook is used to test the Megalodon result

In [1]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y

In [2]:
import pandas as pd
import numpy as np
import sys, os

# Load the data

In [59]:
input_path='/pod/2/li-lab/Ziwei/Nanopore/daily/test/'
#df=pd.read_csv(os.path.join(input_path, 'total.Megalodon.per_read.prob.bed.gz'),compression='gzip', sep='\t')
df=pd.read_csv(os.path.join(input_path, 'total.test.bed'), sep='\t')
print("Data is loading!")

df

Data is loading!

,chr,start,read_id,strand,5hmC_prob,5mC_prob,5C_prob,label
0,KJ477685.1,204,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.435397,0.085058,0.479545,2
1,KJ477685.1,261,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.342189,0.500821,0.156990,2
2,KJ477685.1,261,fe8be0cc-f4c4-49f1-80db-c840a6c7dfe9,-,0.577034,0.057676,0.365290,2
3,KJ477685.1,266,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.065316,0.861569,0.073115,2
4,KJ477685.1,266,fe8be0cc-f4c4-49f1-80db-c840a6c7dfe9,-,0.794235,0.028885,0.176880,2
...,...,...,...,...,...,...,...,...
2492,J02459.1,60,bb826a6c-c88b-45ac-9984-8b9d6bfb2f11,-,0.054875,0.013023,0.932103,0
2493,J02459.1,60,bb91267a-6661-4248-a084-554f231398c1,-,0.030720,0.004392,0.964888,0
2494,J02459.1,60,bb9cee29-89d0-4a68-a4b4-8fe5c000289f,-,0.032703,0.006934,0.960363,0
2495,J02459.1,60,bbee6b4a-acac-4db9-bbb8-2f379918b146,-,0.035734,0.003182,0.961085,0
2496,J02459.1,60,bc26e861-9931-48fb-b4cb-2adc9ccbd2c0,-,0.040249,0.004014,0.955738,0

In [12]:
#Splitting the data into independent and dependent variables
df_feature = df.loc[:,['5hmC_prob','5mC_prob','5C_prob']]
df_class = df.loc[:,['label']].values
df_class = np.squeeze(df_class) #Convert the label into 1d-array

In [37]:
df_class.shape

(2497,)

In [22]:
df['5hmC_prob'] > 0

0       True
1       True
2       True
3       True
4       True
        ...
2492    True
2493    True
2494    True
2495    True
2496    True
Name: 5hmC_prob, Length: 2497, dtype: bool

In [73]:
### three way judge: https://stackoverflow.com/a/20033232
max_conditions = [
    (df[['5hmC_prob','5mC_prob','5C_prob']].max(axis=1) == df['5hmC_prob']),
    (df[['5hmC_prob','5mC_prob','5C_prob']].max(axis=1) == df['5mC_prob']),
    (df[['5hmC_prob','5mC_prob','5C_prob']].max(axis=1) == df['5C_prob'])
    ]

# create a list of the values we want to assign for each condition
values = [2, 1, 0]

# create a new column and use np.select to assign values to it using our lists as arguments
df['pred_max_label'] = np.select(conditions, values)
df

,chr,start,read_id,strand,5hmC_prob,5mC_prob,5C_prob,label,pred_label,pred_new_label
0,KJ477685.1,204,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.435397,0.085058,0.479545,2,2,0
1,KJ477685.1,261,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.342189,0.500821,0.156990,2,2,1
2,KJ477685.1,261,fe8be0cc-f4c4-49f1-80db-c840a6c7dfe9,-,0.577034,0.057676,0.365290,2,2,2
3,KJ477685.1,266,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.065316,0.861569,0.073115,2,2,1
4,KJ477685.1,266,fe8be0cc-f4c4-49f1-80db-c840a6c7dfe9,-,0.794235,0.028885,0.176880,2,2,2
...,...,...,...,...,...,...,...,...,...,...
2492,J02459.1,60,bb826a6c-c88b-45ac-9984-8b9d6bfb2f11,-,0.054875,0.013023,0.932103,0,2,0
2493,J02459.1,60,bb91267a-6661-4248-a084-554f231398c1,-,0.030720,0.004392,0.964888,0,2,0
2494,J02459.1,60,bb9cee29-89d0-4a68-a4b4-8fe5c000289f,-,0.032703,0.006934,0.960363,0,2,0
2495,J02459.1,60,bbee6b4a-acac-4db9-bbb8-2f379918b146,-,0.035734,0.003182,0.961085,0,2,0
2496,J02459.1,60,bc26e861-9931-48fb-b4cb-2adc9ccbd2c0,-,0.040249,0.004014,0.955738,0,2,0

In [60]:
# create a list of condtion
conditions = [
    (df['5hmC_prob'] > 0),
    (df['5hmC_prob'] <= 0) & (df['5mC_prob'] > df['5C_prob']),
    (df['5hmC_prob'] <= 0) & (df['5mC_prob'] <= df['5C_prob'])
    ]

# create a list of the values we want to assign for each condition
values = [2, 1, 0]

# create a new column and use np.select to assign values to it using our lists as arguments
df['pred_label'] = np.select(conditions, values)
df

,chr,start,read_id,strand,5hmC_prob,5mC_prob,5C_prob,label,pred_label
0,KJ477685.1,204,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.435397,0.085058,0.479545,2,2
1,KJ477685.1,261,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.342189,0.500821,0.156990,2,2
2,KJ477685.1,261,fe8be0cc-f4c4-49f1-80db-c840a6c7dfe9,-,0.577034,0.057676,0.365290,2,2
3,KJ477685.1,266,3e547b1a-0a3e-4475-9b70-0cbd7c8c82aa,-,0.065316,0.861569,0.073115,2,2
4,KJ477685.1,266,fe8be0cc-f4c4-49f1-80db-c840a6c7dfe9,-,0.794235,0.028885,0.176880,2,2
...,...,...,...,...,...,...,...,...,...
2492,J02459.1,60,bb826a6c-c88b-45ac-9984-8b9d6bfb2f11,-,0.054875,0.013023,0.932103,0,2
2493,J02459.1,60,bb91267a-6661-4248-a084-554f231398c1,-,0.030720,0.004392,0.964888,0,2
2494,J02459.1,60,bb9cee29-89d0-4a68-a4b4-8fe5c000289f,-,0.032703,0.006934,0.960363,0,2
2495,J02459.1,60,bbee6b4a-acac-4db9-bbb8-2f379918b146,-,0.035734,0.003182,0.961085,0,2
2496,J02459.1,60,bc26e861-9931-48fb-b4cb-2adc9ccbd2c0,-,0.040249,0.004014,0.955738,0,2

In [ ]:
# create a list of condtion
conditions = [
    (max(df['5hmC_prob'], df['5hmC_prob'], df['5hmC_prob'])> 0),
    (df['5hmC_prob'] <= 0) & (df['5mC_prob'] > df['5C_prob']),
    (df['5hmC_prob'] <= 0) & (df['5mC_prob'] <= df['5C_prob'])
    ]

# create a list of the values we want to assign for each condition
values = [2, 1, 0]

# create a new column and use np.select to assign values to it using our lists as arguments
df['pred_label'] = np.select(conditions, values)
df

In [63]:
y_true = np.squeeze(df.loc[:,['label']].values)
y_pred =np.squeeze(df.loc[:,['pred_label']].values)

confusion_matrix(y_true, y_pred)

array([[  0,   0, 999],
       [  0,   0, 999],
       [  0,   0, 499]])

In [66]:
def plot_cm(y_true, y_pred, filename, label = ['5C', '5mC', '5hmC'], figsize=(10,10)):
    """
    Generate matrix plot of confusion matrix with annotations.
    args: 
      y_true:    true label of the data, with shape (nsamples,)
      y_pred:    prediction of the data, with shape (nsamples,)
      filename:  filename of figure file to save
      labels:    string array, name the order of class labels in the confusion matrix.
                 use `clf.classes_` if using scikit-learn models.
                 with shape (nclass,).
                 Caution: original y_true, y_pred and labels must align.
      figsize:   the size of the figure plotted.
    """
    cm = confusion_matrix(y_true, y_pred)
    # Normalise
    cm_sum = np.sum(cm, axis=1, keepdims=True)
    cm_perc = cm / cm_sum.astype(float) * 100
    annot = np.empty_like(cm).astype(str)
    nrows, ncols = cm.shape
    for i in range(nrows):
        for j in range(ncols):
            c = cm[i, j]
            p = cm_perc[i, j]
            s = cm_sum[i]
            annot[i, j] = '%.1f%%\n%d/%d' % (p, c, s)
    
    cmn = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
    cmn = pd.DataFrame(cmn, index=label, columns=label)
    cmn.index.name = 'True label'
    cmn.columns.name = 'Predicted label'
    fig, ax = plt.subplots(figsize=figsize)
    sns.heatmap(cmn, annot=annot, fmt='', ax=ax, cmap="Blues")
#    plt.savefig(filename)

In [69]:
from sklearn.metrics import f1_score
f1_score(y_true, y_pred, average='micro')

0.1998398077693232

In [ ]:
input_path='/pod/2/li-lab/Ziwei/Nanopore/daily/test/'
#df=pd.read_csv(os.path.join(input_path, 'total.Megalodon.per_read.prob.bed.gz'),compression='gzip', sep='\t')
input_file = os.path.join(input_path, 'total.test.bed')

chr	start	read_id	strand	5hmC_prob	5mC_prob	5C_prob	label	pred_label
with open(input_file, 'r') as rf:
    for line in rf:
        record = line.strip().split("\t")
        chrom = record[0]
        start = int(record[1])
        read_id = record[2]
        strand = record[3]
        prob_5hmC = float(record[4])
        prob_5mC = float(record[5])
        prob_5C = float(record[6])
        meth_score = float(np.e ** float(mod_log_prob))  # Calculate mod_prob